### ISSUE TITLE
WARNING: Unable to execute HTTP request: my-bucket.US

### ISSUE THREAD

**Issue by jedierikb** [corley-archive/aws-ant-task#6]
Trying to use s3put to upload some files, but hitting a wall.  Suggestions? Here is what ANT says:

s3put
Region US given but not found in the region to endpoint map. Will use it as an endpoint
Uploading 1 file(s) from C:\dev\my_js\build
Oct 30, 2012 5:51:43 PM com.amazonaws.http.AmazonHttpClient executeHelper
WARNING: Unable to execute HTTP request: my-bucket.US
C:\dev\my_js\ant\build.xml:49: com.amazonaws.AmazonClientException: Unable to execute HTTP request: my-bucket.US

Windows 7, JRE1.6.0_27

**Comment by jedierikb** [comment]
updated to
aws-java-sdk-1.3.22.jar
httpclient-4.2.2.jar
httpcore-4.2.2.jar

but no avail... I think I am doing something wrong.  I can use desktop clients to connect and upload to the bucket.

```
<target name='upload'>
    <s3put key="keykeykey"
           secret="secretsecret"
           bucket="my-bucket"
           dest="site/js/">
        <fileset dir="${basedir}/build">
            <filename name="cool.js"/>
        </fileset>
    </s3put>
</target>
```

**Comment by wdalmut** [comment]
I check with the US region for understand what is the problem. I need few time.

Thanks for your feedback

**Comment by wdalmut** [comment]
Hi,

I've fixed this in #7 can you update the project? Now it works.

**Comment by jedierikb** [comment]
Super, works great now.  Thank you / Grazie.

**Comment by powerchoke** [comment]
I'm doing the same as jedierikb and still getting this same error.  Any ideas?  Thanks  - powerchoke.
